version: "3.2"

services:
  nats:
    image: nats
    container_name: nats
    ports:
      - "8222:8222"
      - "4222:4222"
    command: "--cluster_name NATS --cluster nats://localhost:6222 --http_port 8222 "
    networks: ["nats-network"]
  nats-1:
    image: nats
    container_name: nats-1
    command: "--cluster_name NATS --cluster nats://localhost:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks: ["nats-network"]
    depends_on: ["nats"]
  nats-2:
    image: nats
    container_name: nats-2
    command: "--cluster_name NATS --cluster nats://localhost:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks: ["nats-network"]
    depends_on: ["nats"]


networks:
  nats-network:
    driver: bridge
    name: nats-network
